version: '3'
services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "8080:15672"
  mysql:
    image: mysql:5.7
    ports:
      - "13306:3306"
    environment:
      - "MYSQL_DATABASE=tiantong"
      - "MYSQL_USER=tiantong"
      - "MYSQL_PASSWORD=123456"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
      - "MYSQL_ROOT_PASSWORD="
    command: [
      'mysqld',
      '--character-set-server=utf8mb4',
      '--default-time-zone=+8:00',
      '--lower-case-table-names=1',
      '--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
    ]